name: Docker Build and Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Check AWS CLI Version
      run: aws --version

    - name: Set AWS Environment Variables
      run: |
        export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
        export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        export AWS_REGION=${{ secrets.AWS_REGION }}

    - name: Debug AWS CLI Configuration
      run: aws configure list

    - name: Debug AWS CLI Commands
      run: |
        export AWS_DEBUG=1
        aws ecr get-login-password --region $AWS_REGION | docker login -u AWS --password-stdin ${{ secrets.AWS_ECR_REGISTRY_URI }}

    - name: Build and push Docker image
      run: |
        docker buildx create --use
        docker buildx inspect --bootstrap

        docker buildx build --platform windows/amd64,linux/amd64,linux/arm64 -t ${{ secrets.AWS_ECR_REGISTRY_URI }}:$GITHUB_RUN_NUMBER -t ${{ secrets.AWS_ECR_REGISTRY_URI }}:latest -f Dockerfile .
        docker tag ${{ secrets.AWS_ECR_REGISTRY_URI }}:$GITHUB_RUN_NUMBER ${{ secrets.AWS_ECR_REGISTRY_URI }}
