name: Docker Build and Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli
    - name: Set AWS Credentials and Region
      run: |
        mkdir -p ~/.aws
        echo "[default]" > ~/.aws/credentials
        echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
        echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
        echo "[default]" > ~/.aws/config
        echo "region=${{ secrets.AWS_REGION }}" >> ~/.aws/config
    - name: Debug AWS CLI Configuration
      run: aws configure list

    - name: Login to AWS ECR
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login -u AWS --password-stdin ${{ secrets.AWS_ECR_REGISTRY_URI }}
    - name: Build and push Docker image
      run: |
        docker buildx create --use
        docker buildx inspect --bootstrap
        docker buildx build --platform linux/amd64 -t ${{ secrets.AWS_ECR_REGISTRY_URI }}:$GITHUB_RUN_NUMBER -t ${{ secrets.AWS_ECR_REGISTRY_URI }}:latest --push -f Dockerfile .
        docker tag ${{ secrets.AWS_ECR_REGISTRY_URI }}:$GITHUB_RUN_NUMBER ${{ secrets.AWS_ECR_REGISTRY_URI }}:$GITHUB_RUN_NUMBER
        docker tag ${{ secrets.AWS_ECR_REGISTRY_URI }}:latest ${{ secrets.AWS_ECR_REGISTRY_URI }}:$GITHUB_RUN_NUMBER
        docker push ${{ secrets.AWS_ECR_REGISTRY_URI }}:$GITHUB_RUN_NUMBER
        docker push ${{ secrets.AWS_ECR_REGISTRY_URI }}:$GITHUB_RUN_NUMBER
        docker push ${{ secrets.AWS_ECR_REGISTRY_URI }}:latest
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ECR_REGISTRY_URI: ${{ secrets.AWS_ECR_REGISTRY_URI }}
